version: '3'

services:
  web_php74:
    build:
      context: ./web_php74
    volumes:
      - ./repository/app:/var/www/app
      - ./web_php74/setup/.bashrc:/root/.bashrc
    ports:
      - "80:80"
    working_dir: /var/www/app/
    environment:
      TZ: "Asia/Tokyo"

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Asia/Tokyo"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  php-my-admin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "89:80"
    environment:
      MYSQL_USERNAME: test_user
      MYSQL_ROOT_PASSWORD: test_pass
      PMA_HOST: db
      PMA_PORT: 3306

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"